FROM python:3.11.3
WORKDIR /api

COPY api/requirements.txt api/api.py api/env api/db.py deployment/.env ./
RUN pip3 install -r ./requirements.txt
ENV FLASK_ENV production

#print errors to console
ENV PYTHONUNBUFFERED 1 

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app", "--log-level debug"]

# BUILD
# docker build -f Dockerfile.api -t flask-api .
# RUN
# docker run --rm -p 5000:5000 flask-api